fixed chapter_19 examples error :add http header
unknwon/the-way-to-go_ZH_CN pull request #814
Opened 2021-12-19 15:22 UTC by YichengZhong

您好：
书中19章的goto_v2示例代码，缺少http代码，可能会引起代码功能的问题。
经过本地测试，修改之后代码可用。后面章节应该也存在同样的问题。

    func Add(w http.ResponseWriter, r *http.Request) {
	    url := r.FormValue("url")
	    if url == "" {
		    w.Header().Set("Content-Type", "text/html")  //增加代码
		    fmt.Fprint(w, AddForm)
		    return
	    }
	    key := store.Put(url)
	    fmt.Fprintf(w, "http://localhost:8080/%s", key)
    }

2021-12-20 01:43 UTC, unknwon requested changes
感谢修正，请使用gofmt格式化代码

2021-12-21 06:17 UTC, YichengZhong commented
您好，提交的代码本身应该就已经格式化了。

2021-12-21 08:07 UTC, unknwon commented
<img width="276" alt="CleanShot 2021-12-21 at 16 06 55@2x" src="https://user-images.githubusercontent.com/2946214/146893894-02a2b26b-25ee-4017-a88d-9dc1436c88a4.png">

gofmt用的是tab不是空格

2021-12-21 14:18 UTC, YichengZhong commented
已经修改，感谢提醒。

2021-12-21 14:51 UTC, unknwon approved these changes

2021-12-21 14:51 UTC, merged