更正init函数使用规则存在的错误
unknwon/the-way-to-go_ZH_CN pull request #824
Opened 2022-02-17 10:30 UTC by girlskk

我在使用时发现，在同一个源文件中可以定义多个init函数，而不是只能有一个，同一个源文件中的多个init函数会按照从上到下的顺序执行初始化，请核实，避免后学者看到.

2022-02-24 10:15 UTC, unknwon requested changes

2022-02-24 10:15 UTC, unknwon commented on eBook/04.4.md
> +每个源文件可以包含多个 init 函数，同一个源文件中的 init函数会按照从上到下的顺序执行，如果一个包多个不同源文件包含init函数的话，调用顺序是以文件名的顺序调用。初始化总是以单线程执行，并且按照包的依赖关系顺序执行。
>同一个源文件中的 init函数会按照从上到下的顺序执行，如果一个包多个不同源文件包含init函数的话，调用顺序是以文件名的顺序调用

这个不一定吧，有官方文档正式出处吗？

2022-03-03 06:25 UTC, girlskk commented
To ensure reproducible initialization behavior, build systems are
encouraged to present multiple files belonging to the same package in
lexical file name order to a compiler.

可以多琢磨一下这句话

actors315 ***@***.***> 于2022年3月2日周三 19:14写道：

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In eBook/04.4.md
> <https://github.com/unknwon/the-way-to-go_ZH_CN/pull/824#discussion_r817590658>
> :
>
> > @@ -262,7 +262,7 @@ a, b, c := 5, 7, "abc"
>
>
>
>  变量除了可以在全局声明中初始化，也可以在 init 函数中初始化。这是一类非常特殊的函数，它不能够被人为调用，而是在每个包完成初始化后自动执行，并且执行优先级比 main 函数高。
>
>
>
> -每个源文件都只能包含一个 init 函数。初始化总是以单线程执行，并且按照包的依赖关系顺序执行。
>
> +每个源文件可以包含多个 init 函数，同一个源文件中的 init函数会按照从上到下的顺序执行，如果一个包多个不同源文件包含init函数的话，调用顺序是以文件名的顺序调用。初始化总是以单线程执行，并且按照包的依赖关系顺序执行。
>
>
> 搜了下官方文档相关的描述，看起来是这样的。
> https://go.dev/ref/spec#Package_initialization
>
> func init() { … }
> Multiple such functions may be defined per package, even within a single
> source file. In the package block, the init identifier can be used only to
> declare init functions, yet the identifier itself is not declared
> <https://go.dev/ref/spec#Declarations_and_scope>. Thus init functions
> cannot be referred to from anywhere in a program.
>
> A package with no imports is initialized by assigning initial values to
> all its package-level variables followed by calling all init functions in
> the order they appear in the source, possibly in multiple files, as
> presented to the compiler. If a package has imports, the imported packages
> are initialized before initializing the package itself. If multiple
> packages import a package, the imported package will be initialized only
> once. The importing of packages, by construction, guarantees that there can
> be no cyclic initialization dependencies.
>
> Package initialization—variable initialization and the invocation of init
> functions—happens in a single goroutine, sequentially, one package at a
> time. An init function may launch other goroutines, which can run
> concurrently with the initialization code. However, initialization always
> sequences the init functions: it will not invoke the next one until the
> previous one has returned.
>
> To ensure reproducible initialization behavior, build systems are
> encouraged to present multiple files belonging to the same package in
> lexical file name order to a compiler.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/unknwon/the-way-to-go_ZH_CN/pull/824#discussion_r817590658>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASWTFRYGXXSY4524CJZOE5DU55ERZANCNFSM5OUH6T4A>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-03-03 10:40 UTC, unknwon commented on eBook/04.4.md
> +每个源文件可以包含多个 init 函数，同一个源文件中的 init函数会按照从上到下的顺序执行，如果一个包多个不同源文件包含init函数的话，调用顺序是以文件名的顺序调用。初始化总是以单线程执行，并且按照包的依赖关系顺序执行。
"encouraged" 只是鼓励，并不是语言强制规范的。。

2022-03-04 01:52 UTC, girlskk commented
之前的说法确实不够严谨，我已作出了修改

Joe Chen ***@***.***> 于2022年3月3日周四 18:40写道：

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In eBook/04.4.md
> <https://github.com/unknwon/the-way-to-go_ZH_CN/pull/824#discussion_r818527968>
> :
>
> > @@ -262,7 +262,7 @@ a, b, c := 5, 7, "abc"
>
>  变量除了可以在全局声明中初始化，也可以在 init 函数中初始化。这是一类非常特殊的函数，它不能够被人为调用，而是在每个包完成初始化后自动执行，并且执行优先级比 main 函数高。
>
> -每个源文件都只能包含一个 init 函数。初始化总是以单线程执行，并且按照包的依赖关系顺序执行。
> +每个源文件可以包含多个 init 函数，同一个源文件中的 init函数会按照从上到下的顺序执行，如果一个包多个不同源文件包含init函数的话，调用顺序是以文件名的顺序调用。初始化总是以单线程执行，并且按照包的依赖关系顺序执行。
>
> "encouraged" 只是鼓励，并不是语言强制规范的。。
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/unknwon/the-way-to-go_ZH_CN/pull/824#discussion_r818527968>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASWTFRZPRFQODADNW3ITWJ3U6CJJDANCNFSM5OUH6T4A>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-03-04 09:35 UTC, unknwon approved these changes

2022-03-04 09:36 UTC, unknwon commented on eBook/04.4.md
> +每个源文件可以包含多个 init 函数，同一个源文件中的 init函数会按照从上到下的顺序执行，如果一个包多个不同源文件包含init函数的话，调用顺序官网描述的是：为了初始化行为的重现，鼓励以文件名的顺序调用。初始化总是以单线程执行，并且按照包的依赖关系顺序执行。
```suggestion
每个源文件可以包含多个 init 函数，同一个源文件中的 init函数会按照从上到下的顺序执行，如果一个包有多个源文件包含 init 函数的话，则官方鼓励但不保证以文件名的顺序调用。初始化总是以单线程并且按照包的依赖关系顺序执行。
```

2022-03-04 09:38 UTC, merged