第十四章上半部分
unknwon/the-way-to-go_ZH_CN pull request #836
Opened 2022-04-26 09:13 UTC by loftea

2022-05-14 07:26 UTC, unknwon requested changes

2022-05-14 07:26 UTC, unknwon commented on eBook/14.0.md
> +作为一门 21 世纪的语言，Go 原生支持应用之间的通信（网络，客户端和服务端，分布式计算，参见 [第 15 章](15.0.md)）和程序的并发。程序可以在不同的处理器和计算机上同时执行不同的代码段。Go 语言为构建并发程序的基本代码块是协程 (goroutine) 与通道 (channel)。他们需要语言，编译器，和 runtime 的支持。Go 语言提供的垃圾回收器对并发编程至关重要。
```suggestion
作为一门 21 世纪的语言，Go 原生支持应用之间的通信（网络，客户端和服务端，分布式计算，参见[第 15 章](15.0.md)和程序的并发。程序可以在不同的处理器和计算机上同时执行不同的代码段。Go 语言为构建并发程序的基本代码块是协程 (goroutine) 与通道 (channel)。他们需要语言，编译器，和 runtime 的支持。Go 语言提供的垃圾回收器对并发编程至关重要。
```

2022-05-14 07:26 UTC, unknwon commented on eBook/14.2.md
> +这个模式用到了后边 [14.6 章](14.6.md) 示例 [producer_consumer.go](exercises/chapter_14/producer_consumer.go) 的生产者-消费者模式。通常，需要从包含了地址索引字段 `items` 的容器给通道填入元素。为容器的类型定义一个方法 `Iter()`，返回一个只读的通道（参见第 [14.2.11](14.2.md#14
```suggestion
这个模式用到了后边 [14.6 章](14.6.md)示例 [producer_consumer.go](exercises/chapter_14/producer_consumer.go) 的生产者-消费者模式。通常，需要从包含了地址索引字段 `items` 的容器给通道填入元素。为容器的类型定义一个方法 `Iter()`，返回一个只读的通道（参见第 [14.2.11](14.2.md#14211-通道的方向) 节）`items`，如下：
```

2022-05-14 07:26 UTC, unknwon commented on eBook/14.3.md
> +在 [第 14.2.10 节](14.2.md) 的通道迭代器中，两个协程经常是一个阻塞另外一个。如果程序工作在多核心的机器上，大部分时间只用到了一个处理器。可以通过使用带缓冲（缓冲空间大于 0）的通道来改善。比如，缓冲大小为 100，迭代器在阻塞之前，至少可以从容器获得 100 个元素。如果消费者协程在独立的内核运行，就有可能让协程不会出现阻塞。
```suggestion
在[第 14.2.10 节](14.2.md)的通道迭代器中，两个协程经常是一个阻塞另外一个。如果程序工作在多核心的机器上，大部分时间只用到了一个处理器。可以通过使用带缓冲（缓冲空间大于 0）的通道来改善。比如，缓冲大小为 100，迭代器在阻塞之前，至少可以从容器获得 100 个元素。如果消费者协程在独立的内核运行，就有可能让协程不会出现阻塞。
```

2022-05-14 07:26 UTC, unknwon commented on eBook/14.4.md
> +从不同的并发执行的协程中获取值可以通过关键字 `select` 来完成，它和 `switch` 控制语句非常相似（[章节5.3](05.3.md)）也被称作通信开关；它的行为像是“你准备好了吗”的轮询机制；`select` 监听进入通道的数据，也可以是用通道发送值的时候。
```suggestion
从不同的并发执行的协程中获取值可以通过关键字 `select` 来完成，它和 `switch` 控制语句非常相似（[章节 5.3](05.3.md)）也被称作通信开关；它的行为像是“你准备好了吗”的轮询机制；`select` 监听进入通道的数据，也可以是用通道发送值的时候。
```

2022-05-14 07:26 UTC, unknwon commented on eBook/14.4.md
> +$$
这里的替换有些问题吧？我看github都不能正常渲染

2022-05-14 07:26 UTC, unknwon commented on eBook/14.6.md
> +一个用到 `recover()` 的程序（参见 [第 13.3 节](13.3.md)）停掉了服务器内部一个失败的协程而不影响其他协程的工作。
```suggestion
一个用到 `recover()` 的程序（参见[第 13.3 节](13.3.md)停掉了服务器内部一个失败的协程而不影响其他协程的工作。
```

2022-05-14 20:30 UTC, loftea commented on eBook/14.4.md
> +$$
我用的是数学公式，大意了，忘记 GitHub 不能渲染了。不好意思，还得使用原来的图片。

2022-05-15 05:47 UTC, unknwon commented on eBook/14.4.md
> +$$
小问题，不过好像没看到新的commit推送？

2022-05-17 08:23 UTC, unknwon commented on eBook/14.4.md
> +$$
```suggestion
使用以下序列在协程中计算 pi：开启一个协程来计算公式中的每一项并将结果放入通道，`main()` 函数收集并累加结果，打印出 pi 的近似值。

![](images/14.4_piseries.png?raw=true)

```

2022-05-17 08:24 UTC, unknwon approved these changes
感谢提交！

2022-05-17 08:24 UTC, merged